infostellarinc/starcoder

.circleci/Dockerfile
https://hub.docker.com/r/infostellarinc/starcoder-builder/
=> Add a dockerfile for the starcoder build image

gr-starcoder/lib/CMakeLists.txt, gr-starcoder/lib/ar2300_driver.h, gr-starcoder/lib/ar2300_receiver.h, gr-starcoder/lib/blocking_queue.cc, gr-starcoder/lib/blocking_spsc_queue.cc, gr-starcoder/lib/blocking_spsc_queue.h, gr-starcoder/lib/driver.c, gr-starcoder/lib/init.c
Followup PR based on @anuraaga 's comments
=> STELLAR-1044 [FOLLOWUP] Replace OS pipe in AR2300 driver with blocking queue

api/starcoder.proto, sampleclient/main.go, server/starcoder.go
Change in gRPC API for supporting commands. View https://github.com/infostellarinc/starcoder/pull/43 for context.
=> [STELLAR-1143] Update API for transmission

gr-starcoder/python/plot_waterfall.py, server/starcoder.go
Fixes waterfall which was previously upside down.
Also fixes a bug during command sending where we don't check if a command block actually exists.
=> STELLAR-1193 Correct vertical orientation of waterfall

Gopkg.lock, Gopkg.toml, cmd/serve.go, gr-starcoder/python/plot_waterfall.py, monitoring/exporter.go, monitoring/metrics.go, server/starcoder.go
Right now only exports the number of flowgraphs currently running.
=> STELLAR-1231 Add Prometheus metrics export

gr-starcoder/python/qa_command_source.py
Not sure how this slipped through the cracks..
=> Fix QA command source

build.gradle, flowgraphs/meteor_m2.grc, gr-starcoder/lib/meteor/meteor_image.cc, gr-starcoder/lib/meteor_decoder_sink_impl.cc, gr-starcoder/lib/qa_meteor_decoder.cc, gr-starcoder/lib/qa_meteor_decoder.h, sampleclient/main.go
The actual meteor flowgraph
.. and some missed edge case handling in C++
=> STELLAR-1248 Meteor flowgraph

gr-starcoder/lib/meteor/meteor_decoder.cc, gr-starcoder/lib/meteor/meteor_decoder.h, gr-starcoder/lib/meteor/meteor_packet.cc, gr-starcoder/lib/meteor_decoder_sink_impl.cc, gr-starcoder/lib/qa_meteor_decoder.cc
=> Fix bug in Meteor decoder

flowgraphs/fsk_9600.grc, gr-starcoder/grc/starcoder_ax25_decoder_bm.xml, gr-starcoder/include/starcoder/ax25.h, gr-starcoder/include/starcoder/ax25_decoder_bm.h, gr-starcoder/lib/ax25_decoder_bm_impl.cc, gr-starcoder/lib/ax25_decoder_bm_impl.h, gr-starcoder/lib/meteor/meteor_decoder.h
So we can start testing the simulation UDP software (?) from BA.
Adds a new parameter to the AX.25 Decoder block "Strip Headers"
=> STELLAR-1371 Strip ax25 header from decoder

.circleci/config.yml, build.gradle, gr-recipes/gnuradio-nogui.lwr
Also fixes pybombs build by fixing version of yaml parser. Confirmed on my machine gnuradio builds.
=> Update gnuradio / uhd to latest versions for boost compatibility.

flowgraphs/fsk_9600_ax25_transceiver.grc, flowgraphs/test.grc, sampleclient/main.go, server/starcoder.go
Modify transceiver flowgraph based on Roger's suggestions.
-sps (of GMSK mod block) = 8
-BT (of GMSK mod) = 0.5
-Constant multiplying the signal = 0.8
- parameter for tx_multiply_const
Also adds some logs I found useful when debugging
=> Modify transceiver flowgraph 

tools/builder/run.sh
looks like it adds another folder with the conda version
=> Fix run.sh

.github/CODEOWNERS
Let me know if I should use a different team.
=> Add owners for starcoder.

server/starcoder.go
See https://www.datadoghq.com/blog/engineering/cgo-and-python/
=> Use pyeval_restorethread for finalizing

gr-starcoder/grc/CMakeLists.txt, gr-starcoder/grc/starcoder_radio_source.xml, gr-starcoder/python/CMakeLists.txt, gr-starcoder/python/__init__.py, gr-starcoder/python/radio_source.py
=> Radio source

flowgraphs/fsk_9600_ax25_transceiver.grc, gr-starcoder/grc/CMakeLists.txt, gr-starcoder/grc/starcoder_pmt_to_pdu.xml, gr-starcoder/python/CMakeLists.txt, gr-starcoder/python/__init__.py, gr-starcoder/python/pmt_to_pdu.py
with hardcoded header for customer
=> Hdlc framer

gr-starcoder_utils/apps/receiver_evaluation/README.md, gr-starcoder_utils/apps/receiver_evaluation/config.example.yaml, gr-starcoder_utils/apps/receiver_evaluation/evaluator.grc, gr-starcoder_utils/apps/receiver_evaluation/run_receiver_evaluation.py, gr-starcoder_utils/python/prbs_sink_pdu.py, gr-starcoder_utils/python/qa_prbs_sink_pdu.py
Helper script for running receiver evaluation with a configuration file. View README for details on how it is supposed to be used.
=> Script for receiver evaluation

gr-starcoder_utils/apps/receiver_evaluation/evaluator.grc, gr-starcoder_utils/grc/CMakeLists.txt, gr-starcoder_utils/grc/starcoder_utils_additive_scrambler.xml, gr-starcoder_utils/grc/starcoder_utils_pmt_pass.xml, gr-starcoder_utils/grc/starcoder_utils_rs_decoder.xml, gr-starcoder_utils/grc/starcoder_utils_viterbi_decoder.xml, gr-starcoder_utils/python/CMakeLists.txt, gr-starcoder_utils/python/__init__.py, gr-starcoder_utils/python/additive_scrambler.py, gr-starcoder_utils/python/pmt_pass.py, gr-starcoder_utils/python/rs_decoder.py, gr-starcoder_utils/python/viterbi_decoder.py
This PR introduces hierarchical blocks that wrap the Viterbi decoder, Additive Scrambler, and RS decoder blocks so we can enable and disable them at runtime.
=> Allow enabling and disabling of blocks

flowgraphs/cw_decoder.grc, gr-starcoder/grc/CMakeLists.txt, gr-starcoder/grc/starcoder_threshold_printer.xml, gr-starcoder/python/CMakeLists.txt, gr-starcoder/python/__init__.py, gr-starcoder/python/threshold_printer.py
Convert the custom Python block in the CW flowgraph to a proper block.
=> Fix cw decoder

sampleclient/main.go, server/starcoder.go
=> Exit Starcoder after TCP stream to work around TCP source block bug.

.circleci/config.yml, gr-recipes/gnuradio-nogui.lwr
Fixes https://github.com/infostellarinc/starcoder/issues/148.
=> Fix to an older version of libusb.

.circleci/config.yml, gr-starcoder/grc/CMakeLists.txt, gr-starcoder/grc/starcoder_groundstation_api_doppler.xml, gr-starcoder/python/CMakeLists.txt, gr-starcoder/python/__init__.py, gr-starcoder/python/groundstation_api_doppler.py, gr-starcoder/python/qa_groundstation_api_doppler.py
Will add more tests  + waiting on new release of stellarstation-api v0.3.0
=> STELLAR-2726 Groundstation api doppler block

gr-starcoder/python/groundstation_api_doppler.py
Found via testing with fake server
=> Fix bugs in groundstation_api_doppler block

tools/builder/start_flowgraph.py
This script is used to run/compile-and-run a flowgraph with the given parameters and optionally "collect" and send any files generated by the flowgraph to the ground station API (eg waterfall plots).
=> STELLAR-2792 Flowgraph startup script

gr-starcoder/apps/flowgraphs/bpsk_ax25.grc, gr-starcoder/apps/flowgraphs/fsk_ax100.grc, gr-starcoder/apps/flowgraphs/fsk_ax25.grc, gr-starcoder/apps/flowgraphs/fsk_ccsds.grc, gr-starcoder/apps/flowgraphs/test.grc
plus fix a bug in the other flowgraphs (missing a PMT to PDU block)
=> update test.grc to the new API

gr-starcoder/apps/flowgraphs/bpsk_ax25.grc, gr-starcoder/apps/flowgraphs/fsk_ccsds.grc
`waterfall_image_file_path` did not exist in some flowgraphs.
=> Fix flowgraphs

gr-starcoder/apps/flowgraphs/fsk_ax25.grc
This just removes the hierarchical block, which was causing build issues.
=> Move hierarchical block internals into ax.25 flow graph
