infostellarinc/starcoder

.gitignore, LICENSE.header, api/starcoder.proto, build.gradle
We prefer to use Gradle for building things for smarter incremental compiling and a strong ability to define build dependencies. We also don't like checking in generated code, regardless of the golang recommendations.
=> Build proto with gradle and move to api directory. 

build.gradle, gr-recipes/gnuradio-nogui.lwr, gradle/wrapper/gradle-wrapper.properties
The only dependency is Java, all other native dependencies including compiler toolchain are from miniconda which is automatically set up.
I will later add support for building our blocks and the starcoder binary environment so there are no additional deps.
=> Add a task that automatically build gnuradio

api/starcoder.proto, cmd/serve.go, gr-starcoder/grc/CMakeLists.txt, gr-starcoder/grc/starcoder_enqueue_msg_sink.xml, gr-starcoder/python/CMakeLists.txt, gr-starcoder/python/__init__.py, gr-starcoder/python/enqueue_msg_sink.py, gr-starcoder/python/qa_ar2300_source.py, gr-starcoder/python/qa_enqueue_msg_sink.py, sampleclient/main.go, server/starcoder.go
Adds a block called `enqueue_msg_sink`. Provides method to grab a queue which can then be polled for new entries, so you can do anything with them (sent through gRPC, in our case).
Written in Python for now for simplicity, but performance-wise, this isn't really a bottleneck for us since it is out of the path of GNURadio streaming blocks (it only handles async messages, not samples).
Searches the flowgraph for `enqueue_msg_sink` blocks. User can then call `StreamPmt` for a particular block to get a stream of the messages from that block.
=> Enqueue msg sink

build.gradle, gr-recipes/gnuradio-nogui.lwr
Also downgrades gnuradio since it doesn't compile with our compiler due to a source-code bug with modern compilers. Will look into fixing upstream.
After this, I'll create a Dockerfile that we'll copy the built prefix into. It'll be pretty big, but over time we can figure out what parts of the prefix are necessary at runtime, not just compile time.
=> Install starcoder into prefix during build.

.circleci/config.yml, .dockerignore, Gopkg.lock, Gopkg.toml, build.gradle, gr-recipes/gnuradio-nogui.lwr, tools/builder/Dockerfile, tools/builder/run.sh
The Dockerfile runs the build, including `gnuradio` prefix setup, and copies the prefix into the image. The default command of the image is starcoder.
- Also migrated usages of `go get` to more efficient manual download / `dep ensure`
- Disabled octoclock in `uhd` build for now - I feel like i have previously been able to build with it, but for some reason couldn't, and I feel like there is an obvious bug in their `CMakeLists.txt` so will debug it. Anyways, we don't use octoclock
=> Add dockerfile which prepares a running starcoder image.

cqueue/c_queue.go, cqueue/string_queue.cc, cqueue/string_queue.h, flowgraphs/test.grc, gr-starcoder/include/starcoder/enqueue_message_sink.h, gr-starcoder/include/starcoder/waterfall_plotter.h, gr-starcoder/lib/blocking_spsc_queue.cc, gr-starcoder/lib/enqueue_message_sink_impl.cc, gr-starcoder/lib/enqueue_message_sink_impl.h, gr-starcoder/lib/qa_enqueue_message_sink.cc, gr-starcoder/lib/waterfall_plotter_impl.cc, gr-starcoder/lib/waterfall_plotter_impl.h, gr-starcoder/python/plot_waterfall.py, gr-starcoder/python/waterfall_sink.py, sampleclient/main.go, server/starcoder.go
Adds `register_queue_pointer` method to waterfall plotter and sends back final waterfall plot via `string_queue` (if registered).
Also adds a lock around `string_queue.push()` as per https://github.com/infostellarinc/starcoder/pull/33#discussion_r185179199
=> Send back waterfall plot on a string_queue

.circleci/config.yml
Seems that "build without cache" doesn't re-save the cache. Not sure if bug or feature. See https://discuss.circleci.com/t/does-clear-cache-work-for-2-0/10965/22 particularly the February posts.
The [official docs](https://support.circleci.com/hc/en-us/articles/115015426888-Clear-project-cache) suggest that we just change the cache version everytime we want to clear the cache, so I guess this works.
=> Update Circle cache key

flowgraphs/fsk_9600.grc, flowgraphs/fsk_9600_ax25_transmit.grc, flowgraphs/waterfall_only.grc, gr-starcoder/lib/ar2300_source_impl.cc
Updated fsk_9600, waterfall_only, and fsk_9600_ax25_transmit flowgraphs to have Doppler shifting capability
The Doppler shift compensation is performed by a simple multiplication with a complex exponential. The client will set the amount of shift dynamically through the command source block (PMT type `double`).
=> STELLAR-1202 Add Doppler shifting capability to flowgraphs

tools/builder/Dockerfile
We still need to explicitly turn on the GNURadio performance counter in the runtime config. We can do this either with an environment variable or `$HOME/.gnuradio/config.conf`. I wasn't sure which was the best way to do this.
=> Turn on Perf counter env variable

cqueue/string_queue.cc, gr-starcoder/lib/enqueue_message_sink_impl.cc, gr-starcoder/lib/noaa_apt_sink_impl.cc, server/starcoder.go
Adds error logs so we can narrow down at which stage this bug (unexpected packet > 10MB) happens. Once it is caught, it is not sent through gRPC so the stream can continue.
=> STELLAR-1256 Add debug logs for unexpected packets > 10MB

cqueue/string_queue.h, gr-starcoder/lib/blocking_spsc_queue.h
Similar issues here. 
https://github.com/MusicPlayerDaemon/MPD/issues/265
https://github.com/MusicPlayerDaemon/MPD/pull/266
https://github.com/Homebrew/homebrew-core/pull/26784
It looks like boost 1.67.0 has the bug. What I'm wondering is what triggered the change of version of boost in our build? It doesn't seem like https://github.com/gnuradio/gr-recipes/blob/master/boost.lwr changed (I'm assuming this is what defines the version of boost we use?).
=> fix boost 1.67.0 build failure

.circleci/config.yml, build.gradle
UHD needs to download some additional images after installation to properly operate the USRP. We did this by directly running
`/root/.gradle/curiostack/python/bootstrap/miniconda2-gnuradio/lib/uhd/utils/uhd_images_downloader.py`
in the image.
Dunno if it'll work, let's see what Circle does.
=> STELLAR-1570 run uhd images downloader

cmd/root.go, cmd/serve.go, server/starcoder.go, tools/builder/Dockerfile
Logging that a certain block in Starcoder received a command is very useful, but for blocks like Doppler shift which receive a command hundreds of times a second, very spammy. This PR adds a configuration option to silence logs for a particular command block.
=> Add configuration for suppressing particular command logs

build.gradle, gr-recipes/gr-starcoder.lwr
Just needed to set `PYBOMBS_PREFIX`.
Also created a separate gradle task for now since installing with this command currently can only build our merged code, not unmerged code which we need for PR builds. I think we can override to use a local directory in `gnuradio-nogui.lwr` but haven't looked into it yet.
=> Add a recipe for pybombs user to install gr-starcoder.

flowgraphs/fsk_9600.grc, sampleclient/main.go
We were still using the LPF taps optimized for the old hardware. Replaced it with the rational resampler for a sharper filter.
Old:
New:
=> Change decimation LPF for FSK9600 flowgraph

flowgraphs/aausat4.grc
No change except MTU is now a parameter instead of a variable. For some reason, grcc won't compile if CC Decoder Definition block uses a variable, but has no problem with a parameter..
=> Fix grc compile bug for AAUSAT decoder

flowgraphs/aausat4.grc
Before we push to QA, I wanted to make the AAUSAT decoder work for both non-inverted (QA station) and inverted bitstreams (all the rest of our prod stations).
Previous:
Current:
Main change is I check both inverted and non-inverted bitstreams for the sync word. This is a fairly common solution for this problem.
=> Update AAUSAT flowgraph to work for both inverted and non-inverted bitstreams

build.gradle
Seems `pythonSetup` is gone with https://github.com/infostellarinc/starcoder/pull/80. What should `clangFormat` depend on instead?
=> Fix clangFormat task

tools/builder/Dockerfile
I verified that starcoder starts up but it's hard to actually be confident without also checking a flowgraph.
The raw image goes from 3.5G to 2.9G. I didn't check compressed size, but I guess the difference is much less since much of what's left out is files like `docs`.
=> Copy only needed files to starcoder image.

flowgraphs/fsk_9600.grc, flowgraphs/fsk_9600_ax25_transceiver.grc, flowgraphs/fsk_ax100.grc
FSK demodulator upgraded with newer Symbol Sync module and improved Low pass filter parameters.
Configured parameters tested for optimum GFSK 9600bps performance. Capable (but still not implemented) of different bitrate as well. Tests with AISTECH passes shows +40% performance in successful received packets.
Other changes: AX25 transmitted postamble = 4 on fsk_ax25_9600_transceiver.
There are 3 modified flowgraphs:
-fsk_9600:
-fsk_9600_ax25_transceiver:
-fsk_ax100:
=> fsk demodulator fix init

cmd/serve.go, server/starcoder.go
Currently Starcoder will exit immediately if it get signals.
This change enables that Starcoder wait for finishing flow graph execution before exiting if it get SIGHUP.
=> Graceful shutdown with SIGHUP

flowgraphs/bpsk_ax25.grc
After use of gradle build of stellarstation, previous BPSK AX.25 flowgraph included a custom python block "Strip AX.25 header" thus grcc generated 2 python files and failing its execution.
This block is substituted by "PDU Trim Uniform Vector" already included in starcoder.
=> BPSK AX.25 FIX

gr-starcoder/apps/scripts/start_flowgraph.py
We're replacing PyYaml with ruamel.yaml which is a maintained fork of PyYaml. https://yaml.readthedocs.io/en/latest/pyyaml.html
We ran into this bug https://stackoverflow.com/questions/30458977/yaml-loads-5e-6-as-string-and-not-a-number
=> fix bugs in start_flowgraph.py

gr-starcoder/python/groundstation_api_doppler.py
Fix a timing issue which causes an invalid argument error at `time.sleep()` by passing an negative value.
=> Prevent an timing issue in doppler compensation block
